name: Sync staging branch
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  sync-staging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7.0.1
        with:
          fetch-depth: 0

      - name: Configure Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Force update staging branch
        run: |
          git push --force origin HEAD:staging
